//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace io.thp.psmove {

public enum PSNav_Button {
  NavBtn_CROSS = 0,
  NavBtn_CIRCLE = 1,
  NavBtn_L1 = 4,
  NavBtn_L2 = 5,
  NavBtn_L3 = 7,
  NavBtn_PS = 6,
  NavBtn_UP = 8,
  NavBtn_DOWN = 9,
  NavBtn_LEFT = 10,
  NavBtn_RIGHT = 11
}

}
