//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace io.thp.psmove {

public class PSMoveFusion : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PSMoveFusion(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PSMoveFusion obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PSMoveFusion() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          psmoveapi_csharpPINVOKE.delete_PSMoveFusion(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public PSMoveFusion(PSMoveTracker tracker, float z_near, float z_far) : this(psmoveapi_csharpPINVOKE.new_PSMoveFusion(PSMoveTracker.getCPtr(tracker), z_near, z_far), true) {
  }

  public void get_position(PSMove move, out float arg1, out float arg2, out float arg3) {
    psmoveapi_csharpPINVOKE.PSMoveFusion_get_position(swigCPtr, PSMove.getCPtr(move), out arg1, out arg2, out arg3);
  }

  public PSMoveMatrix4x4 get_projection_matrix() {
    PSMoveMatrix4x4 ret = new PSMoveMatrix4x4(psmoveapi_csharpPINVOKE.PSMoveFusion_get_projection_matrix(swigCPtr), true);
    return ret;
  }

  public PSMoveMatrix4x4 get_modelview_matrix(PSMove move) {
    PSMoveMatrix4x4 ret = new PSMoveMatrix4x4(psmoveapi_csharpPINVOKE.PSMoveFusion_get_modelview_matrix(swigCPtr, PSMove.getCPtr(move)), true);
    return ret;
  }

}

}
