//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace io.thp.psmove {

public class PSMoveTrackerRGBImage : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PSMoveTrackerRGBImage(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PSMoveTrackerRGBImage obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PSMoveTrackerRGBImage() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          psmoveapi_csharpPINVOKE.delete_PSMoveTrackerRGBImage(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_void data {
    set {
      psmoveapi_csharpPINVOKE.PSMoveTrackerRGBImage_data_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = psmoveapi_csharpPINVOKE.PSMoveTrackerRGBImage_data_get(swigCPtr);
      SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
      return ret;
    } 
  }

  public int width {
    set {
      psmoveapi_csharpPINVOKE.PSMoveTrackerRGBImage_width_set(swigCPtr, value);
    } 
    get {
      int ret = psmoveapi_csharpPINVOKE.PSMoveTrackerRGBImage_width_get(swigCPtr);
      return ret;
    } 
  }

  public int height {
    set {
      psmoveapi_csharpPINVOKE.PSMoveTrackerRGBImage_height_set(swigCPtr, value);
    } 
    get {
      int ret = psmoveapi_csharpPINVOKE.PSMoveTrackerRGBImage_height_get(swigCPtr);
      return ret;
    } 
  }

  public int size {
    get {
      int ret = psmoveapi_csharpPINVOKE.PSMoveTrackerRGBImage_size_get(swigCPtr);
      return ret;
    } 
  }

  public PSMoveTrackerRGBImage() : this(psmoveapi_csharpPINVOKE.new_PSMoveTrackerRGBImage(), true) {
  }

}

}
