//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace io.thp.psmove {

class psmoveapi_csharpPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="SWIGRegisterExceptionCallbacks_psmoveapi_csharp")]
    public static extern void SWIGRegisterExceptionCallbacks_psmoveapi_csharp(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_psmoveapi_csharp")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_psmoveapi_csharp(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_psmoveapi_csharp(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_psmoveapi_csharp(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(psmoveapi_csharpPINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(psmoveapi_csharpPINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="SWIGRegisterStringCallback_psmoveapi_csharp")]
    public static extern void SWIGRegisterStringCallback_psmoveapi_csharp(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_psmoveapi_csharp(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static psmoveapi_csharpPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMOVEAPI_VERSION_MAJOR_get___")]
  public static extern int PSMOVEAPI_VERSION_MAJOR_get();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMOVEAPI_VERSION_MINOR_get___")]
  public static extern int PSMOVEAPI_VERSION_MINOR_get();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMOVEAPI_VERSION_PATCH_get___")]
  public static extern int PSMOVEAPI_VERSION_PATCH_get();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMOVE_EXT_DATA_BUF_SIZE_get___")]
  public static extern int PSMOVE_EXT_DATA_BUF_SIZE_get();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_Ext_Device_Info_dev_id_set___")]
  public static extern void PSMove_Ext_Device_Info_dev_id_set(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_Ext_Device_Info_dev_id_get___")]
  public static extern ushort PSMove_Ext_Device_Info_dev_id_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_Ext_Device_Info_dev_info_set___")]
  public static extern void PSMove_Ext_Device_Info_dev_info_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_Ext_Device_Info_dev_info_get___")]
  public static extern global::System.IntPtr PSMove_Ext_Device_Info_dev_info_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_new_PSMove_Ext_Device_Info___")]
  public static extern global::System.IntPtr new_PSMove_Ext_Device_Info();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_delete_PSMove_Ext_Device_Info___")]
  public static extern void delete_PSMove_Ext_Device_Info(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove__PSMove_3AxisVector_x_set___")]
  public static extern void _PSMove_3AxisVector_x_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove__PSMove_3AxisVector_x_get___")]
  public static extern float _PSMove_3AxisVector_x_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove__PSMove_3AxisVector_y_set___")]
  public static extern void _PSMove_3AxisVector_y_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove__PSMove_3AxisVector_y_get___")]
  public static extern float _PSMove_3AxisVector_y_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove__PSMove_3AxisVector_z_set___")]
  public static extern void _PSMove_3AxisVector_z_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove__PSMove_3AxisVector_z_get___")]
  public static extern float _PSMove_3AxisVector_z_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove__PSMove_3AxisVector_v_set___")]
  public static extern void _PSMove_3AxisVector_v_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove__PSMove_3AxisVector_v_get___")]
  public static extern global::System.IntPtr _PSMove_3AxisVector_v_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_new__PSMove_3AxisVector___")]
  public static extern global::System.IntPtr new__PSMove_3AxisVector();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_delete__PSMove_3AxisVector___")]
  public static extern void delete__PSMove_3AxisVector(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove__PSMove_3AxisTransform_row0_set___")]
  public static extern void _PSMove_3AxisTransform_row0_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove__PSMove_3AxisTransform_row0_get___")]
  public static extern global::System.IntPtr _PSMove_3AxisTransform_row0_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove__PSMove_3AxisTransform_row1_set___")]
  public static extern void _PSMove_3AxisTransform_row1_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove__PSMove_3AxisTransform_row1_get___")]
  public static extern global::System.IntPtr _PSMove_3AxisTransform_row1_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove__PSMove_3AxisTransform_row2_set___")]
  public static extern void _PSMove_3AxisTransform_row2_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove__PSMove_3AxisTransform_row2_get___")]
  public static extern global::System.IntPtr _PSMove_3AxisTransform_row2_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove__PSMove_3AxisTransform_m_set___")]
  public static extern void _PSMove_3AxisTransform_m_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove__PSMove_3AxisTransform_m_get___")]
  public static extern global::System.IntPtr _PSMove_3AxisTransform_m_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_new__PSMove_3AxisTransform___")]
  public static extern global::System.IntPtr new__PSMove_3AxisTransform();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_delete__PSMove_3AxisTransform___")]
  public static extern void delete__PSMove_3AxisTransform(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_init___")]
  public static extern int psmove_init(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_set_remote_config___")]
  public static extern void psmove_set_remote_config(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_count_connected___")]
  public static extern int psmove_count_connected();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_connect___")]
  public static extern global::System.IntPtr psmove_connect();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_connect_by_id___")]
  public static extern global::System.IntPtr psmove_connect_by_id(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_connection_type___")]
  public static extern int psmove_connection_type(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_is_remote___")]
  public static extern int psmove_is_remote(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_serial___")]
  public static extern string psmove_get_serial(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_model___")]
  public static extern int psmove_get_model(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_pair___")]
  public static extern int psmove_pair(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_host_pair_custom___")]
  public static extern int psmove_host_pair_custom(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_host_pair_custom_model___")]
  public static extern int psmove_host_pair_custom_model(string jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_pair_custom___")]
  public static extern int psmove_pair_custom(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_set_rate_limiting___")]
  public static extern void psmove_set_rate_limiting(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_set_leds___")]
  public static extern void psmove_set_leds(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2, byte jarg3, byte jarg4);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_set_led_pwm_frequency___")]
  public static extern int psmove_set_led_pwm_frequency(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_set_rumble___")]
  public static extern void psmove_set_rumble(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_update_leds___")]
  public static extern int psmove_update_leds(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_poll___")]
  public static extern int psmove_poll(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_ext_data___")]
  public static extern int psmove_get_ext_data(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_send_ext_data___")]
  public static extern int psmove_send_ext_data(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, byte jarg3);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_buttons___")]
  public static extern uint psmove_get_buttons(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_button_events___")]
  public static extern void psmove_get_button_events(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_is_ext_connected___")]
  public static extern int psmove_is_ext_connected(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_ext_device_info___")]
  public static extern int psmove_get_ext_device_info(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_battery___")]
  public static extern int psmove_get_battery(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_temperature___")]
  public static extern int psmove_get_temperature(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_temperature_in_celsius___")]
  public static extern float psmove_get_temperature_in_celsius(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_trigger___")]
  public static extern byte psmove_get_trigger(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_accelerometer___")]
  public static extern void psmove_get_accelerometer(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_gyroscope___")]
  public static extern void psmove_get_gyroscope(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_magnetometer___")]
  public static extern void psmove_get_magnetometer(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_accelerometer_frame___")]
  public static extern void psmove_get_accelerometer_frame(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_gyroscope_frame___")]
  public static extern void psmove_get_gyroscope_frame(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_magnetometer_vector___")]
  public static extern void psmove_get_magnetometer_vector(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_magnetometer_3axisvector___")]
  public static extern void psmove_get_magnetometer_3axisvector(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_reset_magnetometer_calibration___")]
  public static extern void psmove_reset_magnetometer_calibration(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_save_magnetometer_calibration___")]
  public static extern void psmove_save_magnetometer_calibration(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_magnetometer_calibration_range___")]
  public static extern float psmove_get_magnetometer_calibration_range(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_has_calibration___")]
  public static extern int psmove_has_calibration(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_dump_calibration___")]
  public static extern void psmove_dump_calibration(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_enable_orientation___")]
  public static extern void psmove_enable_orientation(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_has_orientation___")]
  public static extern int psmove_has_orientation(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_orientation___")]
  public static extern void psmove_get_orientation(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_reset_orientation___")]
  public static extern void psmove_reset_orientation(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_set_orientation_fusion_type___")]
  public static extern void psmove_set_orientation_fusion_type(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_set_calibration_pose___")]
  public static extern void psmove_set_calibration_pose(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_set_calibration_transform___")]
  public static extern void psmove_set_calibration_transform(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_identity_gravity_calibration_direction___")]
  public static extern void psmove_get_identity_gravity_calibration_direction(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_transformed_gravity_calibration_direction___")]
  public static extern void psmove_get_transformed_gravity_calibration_direction(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_identity_magnetometer_calibration_direction___")]
  public static extern void psmove_get_identity_magnetometer_calibration_direction(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_transformed_magnetometer_calibration_direction___")]
  public static extern void psmove_get_transformed_magnetometer_calibration_direction(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_set_magnetometer_calibration_direction___")]
  public static extern void psmove_set_magnetometer_calibration_direction(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_set_sensor_data_basis___")]
  public static extern void psmove_set_sensor_data_basis(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_set_sensor_data_transform___")]
  public static extern void psmove_set_sensor_data_transform(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_transformed_magnetometer_direction___")]
  public static extern void psmove_get_transformed_magnetometer_direction(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_transformed_accelerometer_frame_3axisvector___")]
  public static extern void psmove_get_transformed_accelerometer_frame_3axisvector(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_transformed_accelerometer_frame_direction___")]
  public static extern void psmove_get_transformed_accelerometer_frame_direction(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_transformed_gyroscope_frame_3axisvector___")]
  public static extern void psmove_get_transformed_gyroscope_frame_3axisvector(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_disconnect___")]
  public static extern void psmove_disconnect(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_reinit___")]
  public static extern void psmove_reinit();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_util_get_ticks___")]
  public static extern int psmove_util_get_ticks();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_util_get_data_dir___")]
  public static extern string psmove_util_get_data_dir();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_util_get_file_path___")]
  public static extern string psmove_util_get_file_path(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_util_get_system_file_path___")]
  public static extern string psmove_util_get_system_file_path(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_util_get_env_int___")]
  public static extern int psmove_util_get_env_int(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_util_get_env_string___")]
  public static extern string psmove_util_get_env_string(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_util_sleep_ms___")]
  public static extern void psmove_util_sleep_ms(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_free_mem___")]
  public static extern void psmove_free_mem(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_connection_type_get___")]
  public static extern int PSMove_connection_type_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_ax_get___")]
  public static extern int PSMove_ax_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_ay_get___")]
  public static extern int PSMove_ay_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_az_get___")]
  public static extern int PSMove_az_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_gx_get___")]
  public static extern int PSMove_gx_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_gy_get___")]
  public static extern int PSMove_gy_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_gz_get___")]
  public static extern int PSMove_gz_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_mx_get___")]
  public static extern int PSMove_mx_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_my_get___")]
  public static extern int PSMove_my_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_mz_get___")]
  public static extern int PSMove_mz_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_new_PSMove__SWIG_0___")]
  public static extern global::System.IntPtr new_PSMove__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_new_PSMove__SWIG_1___")]
  public static extern global::System.IntPtr new_PSMove__SWIG_1(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_get_accelerometer_frame___")]
  public static extern void PSMove_get_accelerometer_frame(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, out float jarg3, out float jarg4, out float jarg5);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_get_gyroscope_frame___")]
  public static extern void PSMove_get_gyroscope_frame(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, out float jarg3, out float jarg4, out float jarg5);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_get_magnetometer_vector___")]
  public static extern void PSMove_get_magnetometer_vector(global::System.Runtime.InteropServices.HandleRef jarg1, out float jarg2, out float jarg3, out float jarg4);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_enable_orientation___")]
  public static extern void PSMove_enable_orientation(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_has_orientation___")]
  public static extern int PSMove_has_orientation(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_has_calibration___")]
  public static extern int PSMove_has_calibration(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_get_orientation___")]
  public static extern void PSMove_get_orientation(global::System.Runtime.InteropServices.HandleRef jarg1, out float jarg2, out float jarg3, out float jarg4, out float jarg5);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_reset_orientation___")]
  public static extern void PSMove_reset_orientation(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_set_leds___")]
  public static extern void PSMove_set_leds(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_set_rumble___")]
  public static extern void PSMove_set_rumble(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_update_leds___")]
  public static extern int PSMove_update_leds(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_set_rate_limiting___")]
  public static extern void PSMove_set_rate_limiting(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_pair___")]
  public static extern int PSMove_pair(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_pair_custom___")]
  public static extern int PSMove_pair_custom(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_get_serial___")]
  public static extern string PSMove_get_serial(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_is_remote___")]
  public static extern int PSMove_is_remote(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_poll___")]
  public static extern int PSMove_poll(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_get_buttons___")]
  public static extern int PSMove_get_buttons(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_get_button_events___")]
  public static extern void PSMove_get_button_events(global::System.Runtime.InteropServices.HandleRef jarg1, out uint jarg2, out uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_get_battery___")]
  public static extern int PSMove_get_battery(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_get_temperature___")]
  public static extern int PSMove_get_temperature(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_get_temperature_in_celsius___")]
  public static extern float PSMove_get_temperature_in_celsius(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_get_trigger___")]
  public static extern int PSMove_get_trigger(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_delete_PSMove___")]
  public static extern void delete_PSMove(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMOVE_TRACKER_DEFAULT_WIDTH_get___")]
  public static extern int PSMOVE_TRACKER_DEFAULT_WIDTH_get();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMOVE_TRACKER_DEFAULT_HEIGHT_get___")]
  public static extern int PSMOVE_TRACKER_DEFAULT_HEIGHT_get();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMOVE_TRACKER_DEFAULT_FPS_get___")]
  public static extern int PSMOVE_TRACKER_DEFAULT_FPS_get();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMOVE_TRACKER_MAX_CONTROLLERS_get___")]
  public static extern int PSMOVE_TRACKER_MAX_CONTROLLERS_get();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMOVE_TRACKER_CAMERA_ENV_get___")]
  public static extern string PSMOVE_TRACKER_CAMERA_ENV_get();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMOVE_TRACKER_FILENAME_ENV_get___")]
  public static extern string PSMOVE_TRACKER_FILENAME_ENV_get();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMOVE_TRACKER_ROI_SIZE_ENV_get___")]
  public static extern string PSMOVE_TRACKER_ROI_SIZE_ENV_get();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMOVE_TRACKER_COLOR_ENV_get___")]
  public static extern string PSMOVE_TRACKER_COLOR_ENV_get();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMOVE_TRACKER_WIDTH_ENV_get___")]
  public static extern string PSMOVE_TRACKER_WIDTH_ENV_get();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMOVE_TRACKER_HEIGHT_ENV_get___")]
  public static extern string PSMOVE_TRACKER_HEIGHT_ENV_get();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerRGBImage_data_set___")]
  public static extern void PSMoveTrackerRGBImage_data_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerRGBImage_data_get___")]
  public static extern global::System.IntPtr PSMoveTrackerRGBImage_data_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerRGBImage_width_set___")]
  public static extern void PSMoveTrackerRGBImage_width_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerRGBImage_width_get___")]
  public static extern int PSMoveTrackerRGBImage_width_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerRGBImage_height_set___")]
  public static extern void PSMoveTrackerRGBImage_height_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerRGBImage_height_get___")]
  public static extern int PSMoveTrackerRGBImage_height_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerRGBImage_size_get___")]
  public static extern int PSMoveTrackerRGBImage_size_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_new_PSMoveTrackerRGBImage___")]
  public static extern global::System.IntPtr new_PSMoveTrackerRGBImage();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_delete_PSMoveTrackerRGBImage___")]
  public static extern void delete_PSMoveTrackerRGBImage(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_camera_frame_width_set___")]
  public static extern void PSMoveTrackerSettings_camera_frame_width_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_camera_frame_width_get___")]
  public static extern int PSMoveTrackerSettings_camera_frame_width_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_camera_frame_height_set___")]
  public static extern void PSMoveTrackerSettings_camera_frame_height_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_camera_frame_height_get___")]
  public static extern int PSMoveTrackerSettings_camera_frame_height_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_camera_frame_rate_set___")]
  public static extern void PSMoveTrackerSettings_camera_frame_rate_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_camera_frame_rate_get___")]
  public static extern int PSMoveTrackerSettings_camera_frame_rate_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_camera_auto_gain_set___")]
  public static extern void PSMoveTrackerSettings_camera_auto_gain_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_camera_auto_gain_get___")]
  public static extern int PSMoveTrackerSettings_camera_auto_gain_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_camera_gain_set___")]
  public static extern void PSMoveTrackerSettings_camera_gain_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_camera_gain_get___")]
  public static extern int PSMoveTrackerSettings_camera_gain_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_camera_auto_white_balance_set___")]
  public static extern void PSMoveTrackerSettings_camera_auto_white_balance_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_camera_auto_white_balance_get___")]
  public static extern int PSMoveTrackerSettings_camera_auto_white_balance_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_camera_exposure_set___")]
  public static extern void PSMoveTrackerSettings_camera_exposure_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_camera_exposure_get___")]
  public static extern int PSMoveTrackerSettings_camera_exposure_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_camera_brightness_set___")]
  public static extern void PSMoveTrackerSettings_camera_brightness_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_camera_brightness_get___")]
  public static extern int PSMoveTrackerSettings_camera_brightness_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_camera_mirror_set___")]
  public static extern void PSMoveTrackerSettings_camera_mirror_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_camera_mirror_get___")]
  public static extern int PSMoveTrackerSettings_camera_mirror_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_exposure_mode_set___")]
  public static extern void PSMoveTrackerSettings_exposure_mode_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_exposure_mode_get___")]
  public static extern int PSMoveTrackerSettings_exposure_mode_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_calibration_blink_delay_set___")]
  public static extern void PSMoveTrackerSettings_calibration_blink_delay_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_calibration_blink_delay_get___")]
  public static extern int PSMoveTrackerSettings_calibration_blink_delay_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_calibration_diff_t_set___")]
  public static extern void PSMoveTrackerSettings_calibration_diff_t_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_calibration_diff_t_get___")]
  public static extern int PSMoveTrackerSettings_calibration_diff_t_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_calibration_min_size_set___")]
  public static extern void PSMoveTrackerSettings_calibration_min_size_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_calibration_min_size_get___")]
  public static extern int PSMoveTrackerSettings_calibration_min_size_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_calibration_max_distance_set___")]
  public static extern void PSMoveTrackerSettings_calibration_max_distance_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_calibration_max_distance_get___")]
  public static extern int PSMoveTrackerSettings_calibration_max_distance_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_calibration_size_std_set___")]
  public static extern void PSMoveTrackerSettings_calibration_size_std_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_calibration_size_std_get___")]
  public static extern int PSMoveTrackerSettings_calibration_size_std_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_color_mapping_max_age_set___")]
  public static extern void PSMoveTrackerSettings_color_mapping_max_age_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_color_mapping_max_age_get___")]
  public static extern int PSMoveTrackerSettings_color_mapping_max_age_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_dimming_factor_set___")]
  public static extern void PSMoveTrackerSettings_dimming_factor_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_dimming_factor_get___")]
  public static extern float PSMoveTrackerSettings_dimming_factor_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_color_hue_filter_range_set___")]
  public static extern void PSMoveTrackerSettings_color_hue_filter_range_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_color_hue_filter_range_get___")]
  public static extern int PSMoveTrackerSettings_color_hue_filter_range_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_color_saturation_filter_range_set___")]
  public static extern void PSMoveTrackerSettings_color_saturation_filter_range_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_color_saturation_filter_range_get___")]
  public static extern int PSMoveTrackerSettings_color_saturation_filter_range_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_color_value_filter_range_set___")]
  public static extern void PSMoveTrackerSettings_color_value_filter_range_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_color_value_filter_range_get___")]
  public static extern int PSMoveTrackerSettings_color_value_filter_range_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_tracker_adaptive_xy_set___")]
  public static extern void PSMoveTrackerSettings_tracker_adaptive_xy_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_tracker_adaptive_xy_get___")]
  public static extern int PSMoveTrackerSettings_tracker_adaptive_xy_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_tracker_adaptive_z_set___")]
  public static extern void PSMoveTrackerSettings_tracker_adaptive_z_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_tracker_adaptive_z_get___")]
  public static extern int PSMoveTrackerSettings_tracker_adaptive_z_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_color_adaption_quality_t_set___")]
  public static extern void PSMoveTrackerSettings_color_adaption_quality_t_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_color_adaption_quality_t_get___")]
  public static extern float PSMoveTrackerSettings_color_adaption_quality_t_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_color_update_rate_set___")]
  public static extern void PSMoveTrackerSettings_color_update_rate_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_color_update_rate_get___")]
  public static extern float PSMoveTrackerSettings_color_update_rate_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_search_tile_width_set___")]
  public static extern void PSMoveTrackerSettings_search_tile_width_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_search_tile_width_get___")]
  public static extern int PSMoveTrackerSettings_search_tile_width_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_search_tile_height_set___")]
  public static extern void PSMoveTrackerSettings_search_tile_height_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_search_tile_height_get___")]
  public static extern int PSMoveTrackerSettings_search_tile_height_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_search_tiles_horizontal_set___")]
  public static extern void PSMoveTrackerSettings_search_tiles_horizontal_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_search_tiles_horizontal_get___")]
  public static extern int PSMoveTrackerSettings_search_tiles_horizontal_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_search_tiles_count_set___")]
  public static extern void PSMoveTrackerSettings_search_tiles_count_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_search_tiles_count_get___")]
  public static extern int PSMoveTrackerSettings_search_tiles_count_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_roi_adjust_fps_t_set___")]
  public static extern void PSMoveTrackerSettings_roi_adjust_fps_t_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_roi_adjust_fps_t_get___")]
  public static extern int PSMoveTrackerSettings_roi_adjust_fps_t_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_tracker_quality_t1_set___")]
  public static extern void PSMoveTrackerSettings_tracker_quality_t1_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_tracker_quality_t1_get___")]
  public static extern float PSMoveTrackerSettings_tracker_quality_t1_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_tracker_quality_t2_set___")]
  public static extern void PSMoveTrackerSettings_tracker_quality_t2_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_tracker_quality_t2_get___")]
  public static extern float PSMoveTrackerSettings_tracker_quality_t2_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_tracker_quality_t3_set___")]
  public static extern void PSMoveTrackerSettings_tracker_quality_t3_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_tracker_quality_t3_get___")]
  public static extern float PSMoveTrackerSettings_tracker_quality_t3_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_color_update_quality_t1_set___")]
  public static extern void PSMoveTrackerSettings_color_update_quality_t1_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_color_update_quality_t1_get___")]
  public static extern float PSMoveTrackerSettings_color_update_quality_t1_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_color_update_quality_t2_set___")]
  public static extern void PSMoveTrackerSettings_color_update_quality_t2_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_color_update_quality_t2_get___")]
  public static extern float PSMoveTrackerSettings_color_update_quality_t2_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_color_update_quality_t3_set___")]
  public static extern void PSMoveTrackerSettings_color_update_quality_t3_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_color_update_quality_t3_get___")]
  public static extern float PSMoveTrackerSettings_color_update_quality_t3_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_intrinsics_xml_set___")]
  public static extern void PSMoveTrackerSettings_intrinsics_xml_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_intrinsics_xml_get___")]
  public static extern string PSMoveTrackerSettings_intrinsics_xml_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_distortion_xml_set___")]
  public static extern void PSMoveTrackerSettings_distortion_xml_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTrackerSettings_distortion_xml_get___")]
  public static extern string PSMoveTrackerSettings_distortion_xml_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_new_PSMoveTrackerSettings___")]
  public static extern global::System.IntPtr new_PSMoveTrackerSettings();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_delete_PSMoveTrackerSettings___")]
  public static extern void delete_PSMoveTrackerSettings(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_tracker_settings_set_default___")]
  public static extern void psmove_tracker_settings_set_default(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_tracker_new___")]
  public static extern global::System.IntPtr psmove_tracker_new();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_tracker_new_with_settings___")]
  public static extern global::System.IntPtr psmove_tracker_new_with_settings(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_tracker_new_with_camera___")]
  public static extern global::System.IntPtr psmove_tracker_new_with_camera(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_tracker_new_with_camera_and_settings___")]
  public static extern global::System.IntPtr psmove_tracker_new_with_camera_and_settings(int jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_tracker_count_connected___")]
  public static extern int psmove_tracker_count_connected();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_tracker_set_auto_update_leds___")]
  public static extern void psmove_tracker_set_auto_update_leds(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_tracker_get_auto_update_leds___")]
  public static extern int psmove_tracker_get_auto_update_leds(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_tracker_set_dimming___")]
  public static extern void psmove_tracker_set_dimming(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_tracker_get_dimming___")]
  public static extern float psmove_tracker_get_dimming(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_tracker_set_exposure___")]
  public static extern void psmove_tracker_set_exposure(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_tracker_get_exposure___")]
  public static extern int psmove_tracker_get_exposure(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_tracker_enable_deinterlace___")]
  public static extern void psmove_tracker_enable_deinterlace(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_tracker_set_mirror___")]
  public static extern void psmove_tracker_set_mirror(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_tracker_get_mirror___")]
  public static extern int psmove_tracker_get_mirror(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_tracker_enable___")]
  public static extern int psmove_tracker_enable(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_tracker_enable_with_color___")]
  public static extern int psmove_tracker_enable_with_color(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, byte jarg3, byte jarg4, byte jarg5);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_tracker_disable___")]
  public static extern void psmove_tracker_disable(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_tracker_get_color___")]
  public static extern int psmove_tracker_get_color(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_tracker_get_camera_color___")]
  public static extern int psmove_tracker_get_camera_color(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_tracker_set_camera_color___")]
  public static extern int psmove_tracker_set_camera_color(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, byte jarg3, byte jarg4, byte jarg5);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_tracker_get_status___")]
  public static extern int psmove_tracker_get_status(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_tracker_update_image___")]
  public static extern void psmove_tracker_update_image(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_tracker_update___")]
  public static extern int psmove_tracker_update(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_tracker_annotate___")]
  public static extern void psmove_tracker_annotate(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_tracker_get_frame___")]
  public static extern global::System.IntPtr psmove_tracker_get_frame(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_tracker_get_image___")]
  public static extern global::System.IntPtr psmove_tracker_get_image(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_tracker_get_position___")]
  public static extern int psmove_tracker_get_position(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_tracker_get_size___")]
  public static extern void psmove_tracker_get_size(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_tracker_distance_from_radius___")]
  public static extern float psmove_tracker_distance_from_radius(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_tracker_set_distance_parameters___")]
  public static extern void psmove_tracker_set_distance_parameters(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2, float jarg3, float jarg4, float jarg5);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_tracker_free___")]
  public static extern void psmove_tracker_free(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSEYE_FOV_BLUE_DOT_get___")]
  public static extern int PSEYE_FOV_BLUE_DOT_get();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSEYE_FOV_RED_DOT_get___")]
  public static extern int PSEYE_FOV_RED_DOT_get();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveMatrix4x4_m_set___")]
  public static extern void PSMoveMatrix4x4_m_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveMatrix4x4_m_get___")]
  public static extern global::System.IntPtr PSMoveMatrix4x4_m_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveMatrix4x4_at___")]
  public static extern float PSMoveMatrix4x4_at(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_new_PSMoveMatrix4x4___")]
  public static extern global::System.IntPtr new_PSMoveMatrix4x4();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_delete_PSMoveMatrix4x4___")]
  public static extern void delete_PSMoveMatrix4x4(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_fusion_new___")]
  public static extern global::System.IntPtr psmove_fusion_new(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2, float jarg3);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_fusion_get_projection_matrix___")]
  public static extern global::System.IntPtr psmove_fusion_get_projection_matrix(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_fusion_get_modelview_matrix___")]
  public static extern global::System.IntPtr psmove_fusion_get_modelview_matrix(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_fusion_get_position___")]
  public static extern void psmove_fusion_get_position(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_fusion_free___")]
  public static extern void psmove_fusion_free(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTracker_dimming_set___")]
  public static extern void PSMoveTracker_dimming_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTracker_dimming_get___")]
  public static extern float PSMoveTracker_dimming_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTracker_exposure_set___")]
  public static extern void PSMoveTracker_exposure_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTracker_exposure_get___")]
  public static extern int PSMoveTracker_exposure_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_new_PSMoveTracker__SWIG_0___")]
  public static extern global::System.IntPtr new_PSMoveTracker__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_new_PSMoveTracker__SWIG_1___")]
  public static extern global::System.IntPtr new_PSMoveTracker__SWIG_1(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTracker_enable___")]
  public static extern int PSMoveTracker_enable(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTracker_enable_with_color___")]
  public static extern int PSMoveTracker_enable_with_color(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3, int jarg4, int jarg5);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTracker_annotate___")]
  public static extern void PSMoveTracker_annotate(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTracker_disable___")]
  public static extern void PSMoveTracker_disable(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTracker_set_auto_update_leds___")]
  public static extern void PSMoveTracker_set_auto_update_leds(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTracker_get_auto_update_leds___")]
  public static extern int PSMoveTracker_get_auto_update_leds(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTracker_get_color___")]
  public static extern void PSMoveTracker_get_color(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, out byte jarg3, out byte jarg4, out byte jarg5);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTracker_get_camera_color___")]
  public static extern void PSMoveTracker_get_camera_color(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, out byte jarg3, out byte jarg4, out byte jarg5);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTracker_set_camera_color___")]
  public static extern int PSMoveTracker_set_camera_color(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, byte jarg3, byte jarg4, byte jarg5);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTracker_enable_deinterlace___")]
  public static extern void PSMoveTracker_enable_deinterlace(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTracker_set_mirror___")]
  public static extern void PSMoveTracker_set_mirror(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTracker_get_mirror___")]
  public static extern int PSMoveTracker_get_mirror(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTracker_get_status___")]
  public static extern int PSMoveTracker_get_status(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTracker_update_image___")]
  public static extern void PSMoveTracker_update_image(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTracker_update__SWIG_0___")]
  public static extern int PSMoveTracker_update__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTracker_update__SWIG_1___")]
  public static extern int PSMoveTracker_update__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTracker_get_image___")]
  public static extern global::System.IntPtr PSMoveTracker_get_image(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTracker_get_position___")]
  public static extern void PSMoveTracker_get_position(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, out float jarg3, out float jarg4, out float jarg5);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTracker_get_size___")]
  public static extern void PSMoveTracker_get_size(global::System.Runtime.InteropServices.HandleRef jarg1, out int jarg2, out int jarg3);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTracker_distance_from_radius___")]
  public static extern float PSMoveTracker_distance_from_radius(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveTracker_set_distance_parameters___")]
  public static extern void PSMoveTracker_set_distance_parameters(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2, float jarg3, float jarg4, float jarg5);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_delete_PSMoveTracker___")]
  public static extern void delete_PSMoveTracker(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_new_PSMoveFusion___")]
  public static extern global::System.IntPtr new_PSMoveFusion(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2, float jarg3);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_delete_PSMoveFusion___")]
  public static extern void delete_PSMoveFusion(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveFusion_get_position___")]
  public static extern void PSMoveFusion_get_position(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, out float jarg3, out float jarg4, out float jarg5);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveFusion_get_projection_matrix___")]
  public static extern global::System.IntPtr PSMoveFusion_get_projection_matrix(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMoveFusion_get_modelview_matrix___")]
  public static extern global::System.IntPtr PSMoveFusion_get_modelview_matrix(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_init___")]
  public static extern int init(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_set_remote_config___")]
  public static extern void set_remote_config(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_count_connected___")]
  public static extern int count_connected();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_reinit___")]
  public static extern void reinit();
}

}
